services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postservice-matrix1555555-205b.h.aivencloud.com:15568/defaultdb?sslmode=require
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_JyMw4WKd5zGVvOCIM6U
    depends_on:
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: